version: '3.1'
services:
  postgres:    
    restart: always    
    image: postgres:10
    volumes:      
      - ./postgres-data/postgres:/var/lib/postgresql/data
    environment:      
      - POSTGRES_USER=rvivanco
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=challengedb
    ports:
      - "5432:5432"
  app:
    build: .    
    ports:      
      - "5000:5000"
    environment:      
      - POSTGRES_URL=postgres
      - POSTGRES_USER=rvivanco
      - POSTGRES_PASS=pass1234
      - POSTGRES_DB=challengedb
    volumes:      
      - ./app:/app
    depends_on: 
      - postgres
